"use client";
import { useState } from "react";
import { z } from "zod";
import { useWalletSession } from "@/identity/wallet-session";
import { freezeSpec, reviewCandidate } from "@/chain/commands";
import { phaseLabel, type TxPhase } from "@/domain/review/transitions";
const schema=z.object({specId:z.string().min(4).max(96),reviewKey:z.string().min(4).max(96),repositoryUrl:z.string().url().startsWith("https://"),advisoryUrl:z.string().url().startsWith("https://"),requirement:z.string().min(24).max(4000),baseline:z.string().min(1).max(160),candidateVersion:z.string().min(1),candidateCommit:z.string().min(7),patchUrl:z.string().url().startsWith("https://"),testsUrl:z.string().url().startsWith("https://"),deploymentUrl:z.string().url().startsWith("https://")});
type Form=z.infer<typeof schema>;
const initial:Form={specId:"",reviewKey:"",repositoryUrl:"",advisoryUrl:"",requirement:"",baseline:"",candidateVersion:"",candidateCommit:"",patchUrl:"",testsUrl:"",deploymentUrl:""};
function origin(url:string){const u=new URL(url);return `${u.protocol}//${u.host}`}
export function ComposeReview({onClose,onComplete}:{onClose():void;onComplete(reviewKey:string):void}){const w=useWalletSession();const[f,setF]=useState(initial);const[error,setError]=useState("");const[phase,setPhase]=useState<TxPhase>("IDLE");const[step,setStep]=useState<"freeze"|"review">("freeze");const set=(k:keyof Form)=>(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement>)=>setF(v=>({...v,[k]:e.target.value}));async function submit(){setError("");const parsed=schema.safeParse(f);if(!parsed.success){setError(parsed.error.issues[0]?.message||"Check the form.");return}if(!w.address){await w.connect();return}if(!w.correctNetwork){await w.switchNetwork();return}try{const allowed=[origin(f.repositoryUrl),origin(f.advisoryUrl),origin(f.patchUrl),origin(f.testsUrl),origin(f.deploymentUrl)].filter((v,i,a)=>a.indexOf(v)===i);if(step==="freeze"){await freezeSpec(w.address,{specId:f.specId,repositoryUrl:f.repositoryUrl,advisoryUrl:f.advisoryUrl,securityRequirement:f.requirement,baselineRef:f.baseline,allowedOrigins:allowed},u=>setPhase(u.phase));setStep("review");setPhase("IDLE")}await reviewCandidate(w.address,{reviewKey:f.reviewKey,specId:f.specId,candidateVersion:f.candidateVersion,candidateCommit:f.candidateCommit,patchUrl:f.patchUrl,testsUrl:f.testsUrl,deploymentUrl:f.deploymentUrl},u=>setPhase(u.phase));setPhase("STATE_REREAD");onComplete(f.reviewKey)}catch(e:any){setPhase("FAILED");setError(e?.message||"Submission failed.")}}
return <div className="sheet-backdrop" role="dialog" aria-modal="true"><div className="compose-sheet"><div className="sheet-head"><div><div className="eyebrow">security release review</div><h2>{step==="freeze"?"Freeze the requirement":"Submit the candidate"}</h2></div><button className="quiet-button" onClick={onClose}>Close ×</button></div><div className="sheet-body"><div className="field-grid"><div className="field"><label>Specification key</label><input value={f.specId} onChange={set("specId")}/></div><div className="field"><label>Review key</label><input value={f.reviewKey} onChange={set("reviewKey")}/></div></div><div className="field"><label>Repository</label><input value={f.repositoryUrl} onChange={set("repositoryUrl")}/></div><div className="field"><label>Frozen security requirement</label><textarea value={f.requirement} onChange={set("requirement")}/></div><div className="field-grid"><div className="field"><label>Reference advisory</label><input value={f.advisoryUrl} onChange={set("advisoryUrl")}/></div><div className="field"><label>Affected baseline</label><input value={f.baseline} onChange={set("baseline")}/></div></div><div className="field-grid"><div className="field"><label>Candidate version</label><input value={f.candidateVersion} onChange={set("candidateVersion")}/></div><div className="field"><label>Candidate commit</label><input value={f.candidateCommit} onChange={set("candidateCommit")}/></div></div><div className="field"><label>Patch evidence</label><input value={f.patchUrl} onChange={set("patchUrl")}/></div><div className="field"><label>Regression-test evidence</label><input value={f.testsUrl} onChange={set("testsUrl")}/></div><div className="field"><label>Deployment identity evidence</label><input value={f.deploymentUrl} onChange={set("deploymentUrl")}/></div>{phase!=="IDLE"&&<div className="info-box"><b>{phaseLabel(phase)}</b>{phase==="ACCEPTED_PROVISIONAL"&&<> — not final, no release authority exists yet.</>}</div>}{error&&<div className="error-box">{error}</div>}{w.error&&<div className="error-box">{w.error}</div>}<div className="sheet-actions"><button className="secondary-action" onClick={onClose}>Cancel</button><button className="primary-action" onClick={submit} disabled={["AWAITING_SIGNATURE","SUBMITTED","CONSENSUS_RUNNING","FINALIZING"].includes(phase)}>{step==="freeze"?"Freeze & continue":"Run GenLayer review"}</button></div></div></div></div>}
